import{a as b,S as f,i as y}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const L="44868548-19b7672d7149b9084b4c3edb5",v="https://pixabay.com/api/";async function m(e,r=1,a=15){const n={key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:a};return(await b.get(v,{params:n})).data}let d;function p(e){const r=document.querySelector(".gallery"),a=e.map(n=>q(n)).join("");r.innerHTML+=a,d?d.refresh():d=new f(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8})}function q({webformatURL:e,largeImageURL:r,tags:a,likes:n,views:t,comments:o,downloads:s}){return`
    <a href="${r}" class="gallery-link">
      <div class="photo-card">
        <img src="${e}" alt="${a}" loading="lazy" class="gallery-image"/>
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${n}</p>
          <p class="info-item"><b>Views:</b> ${t}</p>
          <p class="info-item"><b>Comments:</b> ${o}</p>
          <p class="info-item"><b>Downloads:</b> ${s}</p>
        </div>
      </div>
    </a>
  `}function w(){const e=document.querySelector(".gallery");e.innerHTML=""}function l(e){y.error({title:"Error",message:e})}function c(e){const r=document.querySelector(".loader");e?r.classList.add("loader-active"):r.classList.remove("loader-active")}function S(){y.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}const E=document.querySelector("#search-form"),u=document.querySelector("#load-more");let i=1,g="";E.addEventListener("submit",O);u.addEventListener("click",M);async function O(e){e.preventDefault();const r=e.currentTarget.elements.query.value.trim();if(!r)return l("Please enter a search query");i=1,g=r,w(),c(!0);try{const a=await m(r,i);if(a.hits.length===0){l("Sorry, there are no images matching your search query. Please try again!"),u.style.display="none";return}p(a.hits),h(a.totalHits)}catch{l("Failed to fetch images")}finally{c(!1)}}async function M(){i+=1,c(!0);try{const e=await m(g,i);p(e.hits),h(e.totalHits),P()}catch{l("Failed to fetch more images")}finally{c(!1)}}function h(e){i*15>=e?(u.style.display="none",S()):u.style.display="block"}function P(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}new f(".gallery a",{overlayOpacity:.8,captions:!0,captionsData:"alt",captionDelay:250});
//# sourceMappingURL=commonHelpers.js.map
